//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//Modified by Bachir, John
//add display names for columns
namespace PurchaseList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }


        [Display(Name = "Package ID:")]
        public int PackageId { get; set; }
        [Display(Name = "Package Name:")]
        public string PkgName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Start Date:")]
        public Nullable<System.DateTime> PkgStartDate { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "End Date:")]
        public Nullable<System.DateTime> PkgEndDate { get; set; }
        [Display(Name = "Description:")]
        public string PkgDesc { get; set; }

        [Display(Name = "Base Price:")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal PkgBasePrice { get; set; }
        [Display(Name = "Agency Commission:")]
        public Nullable<decimal> PkgAgencyCommission { get; set; }
        public string ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
